defaults: &defaults
  docker:
    - image: helpermethod/docker-luarocks:0.3.0
  working_directory: ~/build

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - run: git clone --depth=1 https://github.com/helpermethod/lamda .
      - persist_to_workspace:
          root: /home/lua
          paths:
            - build
  install:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/lua
      - restore_cache:
          keys: 
            - luarocks-{{ checksum 'lamda-dev-1.rockspec' }}
            - luarocks-
      - run: luarocks make --local --only-deps
      - save_cache:
          key: luarocks-{{ checksum 'lamda-dev-1.rockspec' }}
          paths:
            - /home/lua/.luarocks
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/lua
      - run: luarocks test --local -- --coverage

workflows:
  version: 2
  ci:
    jobs:
      - checkout
      - install:
          requires:
            - checkout
      - test:
          requires:
            - install
