defaults: &defaults
  docker:
    - image: helpermethod/docker-luarocks:0.3.0
  working_directory: ~/build

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - run: git clone --depth=1 https://github.com/helpermethod/lamda .
      - persist_to_workspace:
          root: /home/lua
          paths:
            - build
  install:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/lua
      - restore_cache:
          keys: 
            - v1-luarocks-{{ checksum "lamda-dev-1.rockspec" }}
            - v1-luarocks-
      - run: luarocks make --local --only-deps
      - save_cache:
          key: v1-luarocks-{{ checksum "lamda-dev-1.rockspec" }}
          paths:
            - /home/lua/.luarocks
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/lua
      - restore_cache:
          keys:
            - v1-luarocks-{{ checksum "lamda-dev-1.rockspec" }}
            - v1-luarocks-
      - run: ~/.luarocks/bin/luacheck src/ spec/
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/lua
     - run: luarocks test --local -- --coverage
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/lua
      - restore_cache:
          keys: 
            - v1-luarocks-{{ checksum "lamda-dev-1.rockspec" }}
            - v1-luarocks-
      - run: luarocks new_version --tag $CIRCLE_TAG
      - run: luarocks upload lamda-$CIRCLE_TAG-1.rockspec --api-key=$LUAROCKS_API_KEY
workflows:
  version: 2
  ci:
    jobs:
      - checkout:
          filters:
            tags:
              only: /(?:\d+.){2}\d/
      - install:
          requires:
            - checkout
          filters:
            tags:
              only: /(?:\d+.){2}\d/
      - lint:
          requires:
            - install
          filters:
            tags:
              only: /(?:\d+.){2}\d/
      - test:
          requires:
            - lint
          filters:
            tags:
              only: /(?:\d+.){2}\d/
      - release:
          requires:
            - test
          filters:
            tags:
              only: /(?:\d+.){2}\d/
            branches:
              ignore: /.*/
