defaults: &defaults
  docker:
    - image: helpermethod/docker-luarocks:0.4.0
  working_directory: ~/build

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - run: git clone --depth=1 https://github.com/helpermethod/lamda .
      - persist_to_workspace:
          root: /home/lua
          paths:
            - build
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/lua
      - restore_cache:
          keys: 
            - v1-luarocks-test-dependencies{{ checksum "lamda-dev-1.rockspec" }}
            - v1-luarocks-test-dependencies
      - run: luarocks test --local -- --coverage
      - persist_to_workspace:
          root: /home/lua
          paths:
            - build
      - save_cache:
          key: v1-luarocks-test-dependencies{{ checksum "lamda-dev-1.rockspec" }}
          paths:
            - /home/lua/.luarocks
  report:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/lua
      - restore_cache:
          keys:
            - v1-luarocks-test-dependencies{{ checksum "lamda-dev-1.rockspec" }}
            - v1-luarocks-test-dependencies
      - run: ~/.luarocks/bin/luacov-coveralls -e /usr/local/share/lua -e ~/.luarocks -t $COVERALLS_REPO_TOKEN
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/lua
      - restore_cache:
          keys:
            - v1-luarocks-test-dependencies{{ checksum "lamda-dev-1.rockspec" }}
            - v1-luarocks-test-dependencies
      - run: ~/.luarocks/bin/luacheck lamda-dev-1.rockspec
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/lua
      - run: luarocks new_version --tag $CIRCLE_TAG
      - run: luarocks upload lamda-$CIRCLE_TAG-1.rockspec --api-key=$LUAROCKS_API_KEY

workflows:
  version: 2
  ci:
    jobs:
      - checkout:
          filters:
            tags:
              only: /(?:\d+.){2}\d/
      - test:
          requires:
            - checkout
          filters:
            tags:
              only: /(?:\d+.){2}\d/
      - report:
          requires:
            - test
          filters:
            tags:
              only: /(?:\d+.){2}\d/
      - lint:
          requires:
            - report
          filters:
            tags:
              only: /(?:\d+.){2}\d/
      - release:
          requires:
            - lint
          filters:
            tags:
              only: /(?:\d+.){2}\d/
            branches:
              ignore: /.*/
