defaults: &defaults
  docker:
    - image: helpermethod/docker-luarocks:0.3.0
  working_directory: ~/

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - run: git clone --depth=1 https://github.com/helpermethod/lamda
      - persist_to_workspace:
          root: /home/lua
          paths:
            - lamda
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/lua
      - run: luarocks test --local -- --coverage

workflows:
  version: 2
  ci:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
